Increase memory available for app build (#278)
Frontend dockerization is failing with 

> FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap
out of memory

Testing various values, looks like the frontend build requires ~3100MB
of memory.
The PR grants 4GB to be on the safe side.